# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Snell's Blog
email: bensnellstudio@gmail.com
portfolio: http://ben-snell.com
description: > # this means to ignore newlines until "baseurl:"
  Ongoing project documentation of the weird and wonderful
baseurl: "" # the subpath of your site, e.g. /blog
url: "bensnell.github.io" # the base hostname & protocol for your site
twitter_username: lleusueq
github_username:  bensnell

# Build settings
markdown: kramdown
